version: '3.2'
services:
  producer1:
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=producer
  producer2:
    build: ./
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      - rabbitmq
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=producer
  loadbalancer:
    image: nginx
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    tty: true
    links:
      - producer1
      - producer2
    ports:
      - '80:80'
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - 5672:5672
      - 15672:15672